// This file will be auto-generated by the API server
// Export all types and router from the generated server.ts

export type { AppRouter } from './server';
export { normalizeTime } from './utils';
export {
  CLAIM_TYPE,
  CLAIM_STATUS,
  CLAIM_REASON_CATEGORY,
  CLAIM_REASON_CATEGORY_LABELS,
  type ClaimType,
  type ClaimStatus,
  type ClaimReasonCategory,
} from './types/claim';