import { initTRPC } from "@trpc/server";
import { z } from "zod";

// ============================================
// // AUTO-INJECTED IMPORTS (DO NOT EDIT)
// Generated by scripts/inject-definitions.js
// ============================================
import {
  socialMediaPlatformEnumSchema,
  brandManagerSchema,
  campaignProductInputSchema,
  campaignInfluencerInputSchema,
  DATE_FILTER_TYPE_ENUM_VALUE,
  BUSINESS_TYPE_ENUM_VALUE,
  paginationQuerySchema,
  createPaginatedResponseSchema,
  businessInfoSchema,
  bankInfoSchema,
  PRODUCT_TYPE_ENUM_VALUE,
} from './types';
import {
  TIME_FORMAT_REGEX,
  TIME_FORMAT_ERROR_MESSAGE_KO,
  normalizeTime,
} from './utils';
// ============================================

const t = initTRPC.create();
const publicProcedure = t.procedure;

const appRouter = t.router({
  shopProduct: t.router({
    getProductDetail: publicProcedure.input(z.object({
      saleId: z.number(),
    })).output(z.discriminatedUnion('type', [
      z.object({
        id: z.number(),

        // 상품 정보
        name: z.string(),
        thumbnailUrl: z.string().nullish(),
        originalPrice: z.number(),
        price: z.number(),
        description: z.string().nullish(),
        detailHtml: z.string().nullish(),

        // 캠페인 정보
        campaign: z.object({
          id: z.number(),
          title: z.string(),
          startAt: z.date(),
          endAt: z.date(),
        }),

        // 브랜드 정보
        brand: z.object({
          id: z.number(),
          name: z.string(),
        }),

        // 인플루언서 정보
        influencer: z.object({
          id: z.number(),
          name: z.string(),
          slug: z.string().nullish(),
          thumbnail: z.string().nullish(),
        }),
      }).extend({
        type: z.literal('HOTEL'),

        // 호텔 전용 정보
        baseCapacity: z.number(),
        maxCapacity: z.number(),
        checkInTime: z.string(),
        checkOutTime: z.string(),

        // 호텔 옵션
        options: z.object({
          skus: z.array(
            z.object({
              id: z.number(),
              quantity: z.number(),
              date: z.string(),
            })
          ),
          hotelOptions: z.array(
            z.object({
              id: z.number(),
              name: z.string(),
              priceByDate: z.record(z.number()),
            })
          ),
        }),

        // 호텔 판매정보
        salesInfo: z.object({
          seller: z.object({
            companyName: z.string().nullish(), // 업체명
            ceoName: z.string().nullish(), // 대표자명
            address: z.string().nullish(), // 사업장 주소
            licenseNumber: z.string().nullish(), // 사업자등록번호
            mailOrderLicenseNumber: z.string().nullish(), // 통신판매업 신고번호
          }),
          accommodationInfo: z.object({
            checkInTime: z.string().nullish(), // 입실시간
            checkOutTime: z.string().nullish(), // 퇴실시간
            baseCapacity: z.number().nullish(), // 기준인원
            maxCapacity: z.number().nullish(), // 최대인원
            bedTypes: z.array(z.string()).nullish(), // 침대구성
          }),
        }),
      }),
      z.object({
        id: z.number(),

        // 상품 정보
        name: z.string(),
        thumbnailUrl: z.string().nullish(),
        originalPrice: z.number(),
        price: z.number(),
        description: z.string().nullish(),
        detailHtml: z.string().nullish(),

        // 캠페인 정보
        campaign: z.object({
          id: z.number(),
          title: z.string(),
          startAt: z.date(),
          endAt: z.date(),
        }),

        // 브랜드 정보
        brand: z.object({
          id: z.number(),
          name: z.string(),
        }),

        // 인플루언서 정보
        influencer: z.object({
          id: z.number(),
          name: z.string(),
          slug: z.string().nullish(),
          thumbnail: z.string().nullish(),
        }),
      }).extend({
        type: z.literal('DELIVERY'),

        options: z.object({
          // TODO: 배송 상품 옵션 추가
        }),

        // TODO: 배송 판매정보 추가 (deliveryInfo, exchangeReturnInfo, productInfoNotice)
        salesInfo: z.object({
          seller: z.object({
            companyName: z.string().nullish(), // 업체명
            ceoName: z.string().nullish(), // 대표자명
            address: z.string().nullish(), // 사업장 주소
            licenseNumber: z.string().nullish(), // 사업자등록번호
            mailOrderLicenseNumber: z.string().nullish(), // 통신판매업 신고번호
          }),
        }),
      }),
      z.object({
        id: z.number(),

        // 상품 정보
        name: z.string(),
        thumbnailUrl: z.string().nullish(),
        originalPrice: z.number(),
        price: z.number(),
        description: z.string().nullish(),
        detailHtml: z.string().nullish(),

        // 캠페인 정보
        campaign: z.object({
          id: z.number(),
          title: z.string(),
          startAt: z.date(),
          endAt: z.date(),
        }),

        // 브랜드 정보
        brand: z.object({
          id: z.number(),
          name: z.string(),
        }),

        // 인플루언서 정보
        influencer: z.object({
          id: z.number(),
          name: z.string(),
          slug: z.string().nullish(),
          thumbnail: z.string().nullish(),
        }),
      }).extend({
        type: z.literal('E-TICKET'),

        options: z.object({
          // TODO: E-TICKET 상품 옵션 추가
        }),

        salesInfo: z.object({
          seller: z.object({
            companyName: z.string().nullish(), // 업체명
            ceoName: z.string().nullish(), // 대표자명
            address: z.string().nullish(), // 사업장 주소
            licenseNumber: z.string().nullish(), // 사업자등록번호
            mailOrderLicenseNumber: z.string().nullish(), // 통신판매업 신고번호
          }),
        }),
      }),
    ])).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  shopPayment: t.router({
    complete: publicProcedure.input(z.object({
      paymentId: z.string(),
      paymentToken: z.string(),
      transactionType: z.string(),
      txId: z.string(),
    })).output(z.object({
      success: z.boolean(),
      message: z.string(),
      orderNumber: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  shopOrder: t.router({
    createHotelOrder: publicProcedure.input(z.object({
      saleId: z.number(),
      checkInDate: z.string(),
      checkOutDate: z.string(),
      optionId: z.number(),
    })).output(z.object({
      orderNumber: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getTmpOrder: publicProcedure.input(z.object({
      orderNumber: z.string(),
    })).output(z.object({
      type: z.enum(PRODUCT_TYPE_ENUM_VALUE),
      totalAmount: z.number(),
      product: z.object({
        name: z.string(),
        thumbnailUrl: z.string().nullish(),
        checkInTime: z.string(),
        checkOutTime: z.string(),
      }),
      orderOptionSnapshot: z.object({
        type: z.literal('HOTEL'),
        checkInDate: z.string(),
        checkOutDate: z.string(),
        hotelOptionId: z.number(),
        hotelOptionName: z.string(),
        priceByDate: z.record(z.string(), z.number()),
      }),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    updateTmpOrder: publicProcedure.input(z.object({
      orderNumber: z.string(),
      customerName: z.string(),
      customerPhone: z.string(),
    })).output(z.object({
      success: z.boolean(),
      customerName: z.string(),
      customerPhone: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getOrderDetail: publicProcedure.input(z.object({
      orderNumber: z.string(),
    })).output(z.object({
      type: z.literal('accommodation'),
      orderId: z.number(),
      orderNumber: z.string(),
      orderDate: z.string(),
      status: z.string(),
      statusDescription: z.string().nullish(),
      influencerSlug: z.string().nullish(),
      accommodation: z.object({
        thumbnail: z.string().nullish(),
        hotelName: z.string(),
        roomName: z.string(),
        optionName: z.string(),
      }),
      checkIn: z.object({
        date: z.string(),
        time: z.string(),
      }),
      checkOut: z.object({
        date: z.string(),
        time: z.string(),
      }),
      user: z.object({
        name: z.string(),
        phone: z.string(),
      }),
      payment: z.object({
        totalAmount: z.number(),
        productAmount: z.number(),
        paymentMethod: z.string(),
      }),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getMyOrders: publicProcedure.input(z.object({
      offset: z.number().optional().default(0),
      limit: z.number().optional().default(20),
    })).output(z.object({
      orders: z.array(z.discriminatedUnion('type', [
        z.object({
          orderId: z.number(),
          orderNumber: z.string(),
          orderDate: z.string(),
          status: z.string(),
          statusDescription: z.string().nullish(),
          totalAmount: z.number(),
          /** 상품 상세 페이지 이동용 */
          influencerSlug: z.string(),
          saleId: z.number(),
        }).extend({
          type: z.literal('HOTEL'),
          accommodation: z.object({
            thumbnail: z.string().nullish(),
            hotelName: z.string(),
            roomName: z.string(),
            optionName: z.string(),
          }),
          checkIn: z.object({
            date: z.string(),
            time: z.string(),
          }),
          checkOut: z.object({
            date: z.string(),
            time: z.string(),
          }),
        }),
        z.object({
          orderId: z.number(),
          orderNumber: z.string(),
          orderDate: z.string(),
          status: z.string(),
          statusDescription: z.string().nullish(),
          totalAmount: z.number(),
          /** 상품 상세 페이지 이동용 */
          influencerSlug: z.string(),
          saleId: z.number(),
        }).extend({
          type: z.literal('DELIVERY'),
          products: z.array(
            z.object({
              thumbnail: z.string().nullish(),
              name: z.string(),
              option: z.string(),
              price: z.number(),
              quantity: z.number(),
            })
          ),
        }),
      ])),
      total: z.number(),
      hasMore: z.boolean(),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  shopInfluencer: t.router({
    findBySlug: publicProcedure.input(z.object({
      slug: z.string(),
    })).output(z.object({
      id: z.number(),
      slug: z.string(),
      name: z.string(),
      thumbnail: z.string().nullable(),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getCampaigns: publicProcedure.input(z.object({
      slug: z.string(),
    })).output(z.object({
      campaigns: z.array(z.object({
        id: z.number(),
        title: z.string(),
        startAt: z.date(),
        endAt: z.date(),
        products: z.array(z.object({
          id: z.number(),
          saleId: z.number(),
          name: z.string(),
          thumbnail: z.string().nullable(),
          price: z.number(),
          saleStartAt: z.date().nullable(),
        })),
      })),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getCampaignDetail: publicProcedure.input(z.object({
      slug: z.string(),
      campaignId: z.number(),
    })).output(z.object({
      id: z.number(),
      title: z.string(),
      startAt: z.date(),
      endAt: z.date(),
      products: z.array(z.object({
        id: z.number(),
        saleId: z.number(),
        name: z.string(),
        thumbnail: z.string().nullable(),
        originalPrice: z.number(),
        price: z.number(),
      })),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  shopAuth: t.router({
    requestVerification: publicProcedure.input(z.object({
      phone: z
        .string()
        .regex(/^01[0-9]{8,9}$/, '올바른 휴대폰 번호를 입력해주세요'),
    })).output(z.object({
      id: z.number(),
      phone: z.string(),
      expiresAt: z.date(),
      code: z.string().optional(), // 개발환경에서만 노출
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    verifyCode: publicProcedure.input(z.object({
      phone: z.string(),
      code: z.string().length(6, '인증번호 6자리를 입력해주세요'),
    })).output(z.object({
      accessToken: z.string(),
      refreshToken: z.string(),
      member: z.object({
        id: z.number(),
        phone: z.string(),
        name: z.string().nullable(),
      }),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    refreshToken: publicProcedure.input(z.object({
      refreshToken: z.string(),
    })).output(z.object({
      accessToken: z.string(),
      refreshToken: z.string(),
      member: z.object({
        id: z.number(),
        phone: z.string(),
        name: z.string().nullable(),
      }),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    kakaoLogin: publicProcedure.input(z.object({
      code: z.string().min(1, 'Authorization code is required'),
      redirectUri: z.string().url('Valid redirect URI is required'),
    })).output(z.discriminatedUnion('status', [
      z.object({
        status: z.literal('complete'),
        accessToken: z.string(),
        refreshToken: z.string(),
        member: z.object({
          id: z.number(),
          phone: z.string(),
          name: z.string().nullable(),
        }),
      }),
      z.object({
        status: z.literal('pending'),
        pendingToken: z.string(),
        name: z.string().nullable(),
      }),
    ])).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    completeSocialRegistration: publicProcedure.input(z.object({
      pendingToken: z.string(),
      phone: z
        .string()
        .regex(/^01[0-9]{8,9}$/, '올바른 휴대폰 번호를 입력해주세요'),
      code: z.string().length(6, '인증번호 6자리를 입력해주세요'),
    })).output(z.object({
      accessToken: z.string(),
      refreshToken: z.string(),
      member: z.object({
        id: z.number(),
        phone: z.string(),
        name: z.string().nullable(),
      }),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  backofficeUpload: t.router({
    generatePresignedUrl: publicProcedure.input(z.object({
      fileName: z.string().min(1, '파일명은 필수입니다'),
      fileType: z.string().min(1, '파일 타입은 필수입니다'),
      path: z.string().default('uploads'),
      expiresIn: z.number().min(60).max(3600).default(300),
    })).output(z.object({
      uploadUrl: z.string(),
      fileUrl: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  backofficeProductTemplate: t.router({
    findAll: publicProcedure.input(z
      .object({
        // 상품 타입 (숙박/배송상품/티켓)
        type: z.enum(PRODUCT_TYPE_ENUM_VALUE).optional(),

        // 품목명 검색 (템플릿 이름)
        name: z.string().optional(),

        // 날짜 필터 타입 (등록일/수정일)
        dateFilterType: z.enum(DATE_FILTER_TYPE_ENUM_VALUE).optional(),

        // 시작일
        startDate: z.string().datetime().optional(),

        // 종료일
        endDate: z.string().datetime().optional(),

        // 재고 관리 여부 (미지정 시 전체)
        useStock: z.boolean().optional(),

        // 연동 여부 (미지정 시 전체)
        isIntegrated: z.boolean().optional(),

        // 브랜드 ID 목록
        brandIds: z.array(z.number().int().positive()).optional(),

        // 카테고리 ID 목록
        categoryIds: z.array(z.number().int().positive()).optional(),
      })
      .merge(paginationQuerySchema).optional().default({})).output(createPaginatedResponseSchema(z.object({
        id: z.number(),
        type: z.enum(PRODUCT_TYPE_ENUM_VALUE),
        name: z.string(),
        brand: z.object({
          id: z.number(),
          name: z.string(),
        }),
        categories: z.array(
          z.object({
            id: z.number(),
            name: z.string(),
          })
        ),
        isIntegrated: z.boolean(),
        useStock: z.boolean(),
        createdAt: z.date(),
        updatedAt: z.date(),
      }))).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findById: publicProcedure.input(z.object({
      id: z.number().int().positive('유효한 ID를 입력해주세요'),
    })).output(z.discriminatedUnion('type', [
      // Hotel Detail
      z.object({
        type: z.literal('HOTEL'),
        id: z.number(),
        name: z.string(),
        brandId: z.number(),
        brand: z.object({
          id: z.number(),
          name: z.string(),
        }),
        categories: z.array(
          z.object({
            id: z.number(),
            name: z.string(),
          })
        ),
        thumbnailUrls: z.array(z.string()),
        description: z.string(),
        detailContent: z.string(),
        useStock: z.boolean(),
        baseCapacity: z.number(),
        maxCapacity: z.number(),
        checkInTime: z.string(),
        checkOutTime: z.string(),
        bedTypes: z.array(z.string()),
        tags: z.array(z.string()),
        createdAt: z.date(),
        updatedAt: z.date(),
      }),
      // Delivery Detail
      z.object({
        type: z.literal('DELIVERY'),
        id: z.number(),
        name: z.string(),
        brandId: z.number(),
        brand: z.object({
          id: z.number(),
          name: z.string(),
        }),
        categories: z.array(
          z.object({
            id: z.number(),
            name: z.string(),
          })
        ),
        thumbnailUrls: z.array(z.string()),
        description: z.string(),
        detailContent: z.string(),
        useStock: z.boolean(),
        useOptions: z.boolean(),
        delivery: z.object({
          deliveryFeeType: z.string(),
          deliveryFee: z.number(),
          freeDeliveryMinAmount: z.number(),
          returnDeliveryFee: z.number(),
          exchangeDeliveryFee: z.number(),
          remoteAreaExtraFee: z.number(),
          jejuExtraFee: z.number(),
          isJejuRestricted: z.boolean(),
          isRemoteIslandRestricted: z.boolean(),
        }),
        exchangeReturnInfo: z.string(),
        productInfoNotice: z.string(),
        createdAt: z.date(),
        updatedAt: z.date(),
      }),
      // ETicket Detail
      z.object({
        type: z.literal('E-TICKET'),
        id: z.number(),
        name: z.string(),
        brandId: z.number(),
        brand: z.object({
          id: z.number(),
          name: z.string(),
        }),
        categories: z.array(
          z.object({
            id: z.number(),
            name: z.string(),
          })
        ),
        thumbnailUrls: z.array(z.string()),
        description: z.string(),
        detailContent: z.string(),
        useStock: z.boolean(),
        useOptions: z.boolean(),
        createdAt: z.date(),
        updatedAt: z.date(),
      }),
    ])).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure.input(z.discriminatedUnion('type', [
      // Hotel Template
      z.object({
        type: z.literal('HOTEL'),
        name: z.string().min(1, '상품명은 필수입니다'),
        brandId: z.number().int().positive('브랜드를 선택해주세요'),
        categoryIds: z.array(z.number().int().positive()).default([]),
        thumbnailUrls: z.array(z.string().url()).default([]),
        description: z.string().default(''),
        detailContent: z.string().default(''),
        useStock: z.boolean().default(false),
        baseCapacity: z
          .number()
          .int()
          .positive('기준인원은 1명 이상이어야 합니다'),
        maxCapacity: z
          .number()
          .int()
          .positive('최대인원은 1명 이상이어야 합니다'),
        checkInTime: z
          .string()
          .regex(TIME_FORMAT_REGEX)
          .transform(normalizeTime),
        checkOutTime: z
          .string()
          .regex(TIME_FORMAT_REGEX)
          .transform(normalizeTime),
        bedTypes: z.array(z.string()).default([]),
        tags: z.array(z.string()).default([]),
      }),
      // Delivery Template
      z.object({
        type: z.literal('DELIVERY'),
        name: z.string().min(1, '상품명은 필수입니다'),
        brandId: z.number().int().positive('브랜드를 선택해주세요'),
        categoryIds: z.array(z.number().int().positive()).default([]),
        thumbnailUrls: z.array(z.string().url()).default([]),
        description: z.string().default(''),
        detailContent: z.string().default(''),
        useStock: z.boolean().default(false),
        useOptions: z.boolean().default(false),
        delivery: z.object({
          deliveryFeeType: z.enum(['FREE', 'PAID', 'CONDITIONAL_FREE']),
          deliveryFee: z.number().int().nonnegative().default(0),
          freeDeliveryMinAmount: z.number().int().nonnegative().default(0),
          returnDeliveryFee: z.number().int().nonnegative().default(0),
          exchangeDeliveryFee: z.number().int().nonnegative().default(0),
          remoteAreaExtraFee: z.number().int().nonnegative().default(0),
          jejuExtraFee: z.number().int().nonnegative().default(0),
          isJejuRestricted: z.boolean().default(false),
          isRemoteIslandRestricted: z.boolean().default(false),
        }),
        exchangeReturnInfo: z.string().default(''),
        productInfoNotice: z.string().default(''),
      }),
      // ETicket Template
      z.object({
        type: z.literal('E-TICKET'),
        name: z.string().min(1, '상품명은 필수입니다'),
        brandId: z.number().int().positive('브랜드를 선택해주세요'),
        categoryIds: z.array(z.number().int().positive()).default([]),
        thumbnailUrls: z.array(z.string().url()).default([]),
        description: z.string().default(''),
        detailContent: z.string().default(''),
        useStock: z.boolean().default(false),
        useOptions: z.boolean().default(false),
      }),
    ])).output(z.object({
      id: z.number(),
      type: z.enum(['HOTEL', 'E-TICKET', 'DELIVERY']),
      name: z.string(),
      message: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure.input(z.object({
      id: z.number().int().positive('유효한 ID를 입력해주세요'),
      name: z.string().min(1, '상품명은 필수입니다'),
      brandId: z.number().int().positive('브랜드를 선택해주세요'),
      categoryIds: z.array(z.number().int().positive()).optional(),
      thumbnailUrls: z.array(z.string().url()).optional(),
      description: z.string().optional(),
      detailContent: z.string().optional(),
      useStock: z.boolean().optional(),
      // Hotel 전용 필드
      baseCapacity: z.number().int().positive().optional(),
      maxCapacity: z.number().int().positive().optional(),
      checkInTime: z
        .string()
        .regex(TIME_FORMAT_REGEX)
        .transform(normalizeTime)
        .optional(),
      checkOutTime: z
        .string()
        .regex(TIME_FORMAT_REGEX)
        .transform(normalizeTime)
        .optional(),
      bedTypes: z.array(z.string()).optional(),
      tags: z.array(z.string()).optional(),
      // Delivery 전용 필드
      useOptions: z.boolean().optional(),
      delivery: z
        .object({
          deliveryFeeType: z.enum(['FREE', 'PAID', 'CONDITIONAL_FREE']),
          deliveryFee: z.number().int().nonnegative().optional(),
          freeDeliveryMinAmount: z.number().int().nonnegative().optional(),
          returnDeliveryFee: z.number().int().nonnegative().optional(),
          exchangeDeliveryFee: z.number().int().nonnegative().optional(),
          remoteAreaExtraFee: z.number().int().nonnegative().optional(),
          jejuExtraFee: z.number().int().nonnegative().optional(),
          isJejuRestricted: z.boolean().optional(),
          isRemoteIslandRestricted: z.boolean().optional(),
        })
        .optional(),
      exchangeReturnInfo: z.string().optional(),
      productInfoNotice: z.string().optional(),
    })).output(z.object({
      id: z.number(),
      name: z.string(),
      message: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure.input(z.object({
      id: z.number().int().positive('유효한 ID를 입력해주세요'),
    })).output(z.object({
      id: z.number(),
      message: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  backofficeProduct: t.router({
    findAll: publicProcedure.input(z
      .object({
        page: z.number().int().min(1).default(1),
        limit: z.number().int().positive().default(30),
        orderBy: z.string().default('createdAt'),
        order: z.enum(['ASC', 'DESC']).default('DESC'),
        type: z.enum(['HOTEL', 'E-TICKET', 'DELIVERY']).nullish(),
        name: z.string().nullish(),
        status: z.enum(['VISIBLE', 'HIDDEN', 'SOLD_OUT']).nullish(),
        brandIds: z.array(z.number().int()).nullish(),
        ids: z.array(z.number().int().positive()).nullish(),
        dateFilterType: z
          .enum(['CREATED_AT', 'UPDATED_AT'])
          .default('CREATED_AT'),
        startDate: z.string().nullish(),
        endDate: z.string().nullish(),
      })
      .nullish()
      .default({})).output(z.object({
        data: z.array(
          z.object({
            id: z.number(),
            type: z.enum(['HOTEL', 'E-TICKET', 'DELIVERY']),
            name: z.string(),
            brand: z.object({
              id: z.number(),
              name: z.string(),
            }),
            thumbnailUrls: z.array(z.string()),
            price: z.number(),
            status: z.enum(['VISIBLE', 'HIDDEN', 'SOLD_OUT']),
            useStock: z.boolean(),
            useCalendar: z.boolean(),
            createdAt: z.date(),
            updatedAt: z.date(),
          })
        ),
        total: z.number(),
        page: z.number(),
        limit: z.number(),
        totalPages: z.number(),
      })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findById: publicProcedure.input(z.object({
      id: z.number().int().positive('유효한 ID를 입력해주세요'),
    })).output(z.discriminatedUnion('type', [
      // Hotel Detail
      z.object({
        type: z.literal('HOTEL'),
        id: z.number(),
        name: z.string(),
        brandId: z.number(),
        brandName: z.string(),
        productTemplateId: z.number().nullish(),
        campaignId: z.number().nullish(),
        thumbnailUrls: z.array(z.string()),
        description: z.string(),
        detailContent: z.string(),
        useCalendar: z.boolean(),
        useStock: z.boolean(),
        useOptions: z.boolean(),
        price: z.number(),
        status: z.enum(['VISIBLE', 'HIDDEN', 'SOLD_OUT']),
        displayOrder: z.number().nullish(),
        baseCapacity: z.number(),
        maxCapacity: z.number(),
        checkInTime: z.string(),
        checkOutTime: z.string(),
        bedTypes: z.array(z.string()),
        tags: z.array(z.string()),
        hotelOptions: z.array(
          z.object({
            id: z.number(),
            name: z.string(),
            priceByDate: z.record(z.string(), z.number()),
            anotherPriceByDate: z.record(
              z.string(),
              z.object({
                supplyPrice: z.number(),
                commission: z.number(),
              })
            ),
          })
        ),
        hotelSkus: z.array(
          z.object({
            checkInDate: z.string(),
            quantity: z.number(),
          })
        ),
        createdAt: z.date(),
        updatedAt: z.date(),
      }),
      // Delivery Detail
      z.object({
        type: z.literal('DELIVERY'),
        id: z.number(),
        name: z.string(),
        brandId: z.number(),
        brandName: z.string(),
        productTemplateId: z.number().nullish(),
        campaignId: z.number().nullish(),
        thumbnailUrls: z.array(z.string()),
        description: z.string(),
        detailContent: z.string(),
        useCalendar: z.boolean(),
        useStock: z.boolean(),
        useOptions: z.boolean(),
        price: z.number(),
        status: z.enum(['VISIBLE', 'HIDDEN', 'SOLD_OUT']),
        displayOrder: z.number().nullish(),
        delivery: z.object({
          deliveryFeeType: z.enum(['FREE', 'PAID', 'CONDITIONAL_FREE']),
          deliveryFee: z.number().int().nonnegative().default(0),
          freeDeliveryMinAmount: z.number().int().nonnegative().default(0),
          returnDeliveryFee: z.number().int().nonnegative().default(0),
          exchangeDeliveryFee: z.number().int().nonnegative().default(0),
          remoteAreaExtraFee: z.number().int().nonnegative().default(0),
          jejuExtraFee: z.number().int().nonnegative().default(0),
          isJejuRestricted: z.boolean().default(false),
          isRemoteIslandRestricted: z.boolean().default(false),
        }),
        exchangeReturnInfo: z.string(),
        productInfoNotice: z.string(),
        createdAt: z.date(),
        updatedAt: z.date(),
      }),
      // ETicket Detail
      z.object({
        type: z.literal('E-TICKET'),
        id: z.number(),
        name: z.string(),
        brandId: z.number(),
        brandName: z.string(),
        productTemplateId: z.number().nullish(),
        campaignId: z.number().nullish(),
        thumbnailUrls: z.array(z.string()),
        description: z.string(),
        detailContent: z.string(),
        useCalendar: z.boolean(),
        useStock: z.boolean(),
        useOptions: z.boolean(),
        price: z.number(),
        status: z.enum(['VISIBLE', 'HIDDEN', 'SOLD_OUT']),
        displayOrder: z.number().nullish(),
        createdAt: z.date(),
        updatedAt: z.date(),
      }),
    ])).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure.input(z.discriminatedUnion('type', [
      // Hotel Product
      z.object({
        type: z.literal('HOTEL'),
        name: z.string().min(1, '상품명은 필수입니다'),
        brandId: z.number().int().positive('브랜드를 선택해주세요'),
        productTemplateId: z.number().int().positive().nullish(),
        campaignId: z.number().int().positive().nullish(),
        categoryIds: z.array(z.number().int().positive()).default([]),
        thumbnailUrls: z.array(z.string().url()).default([]),
        description: z.string().default(''),
        detailContent: z.string().default(''),
        useCalendar: z.literal(true),
        useStock: z.boolean().default(false),
        useOptions: z.boolean().default(false),
        price: z.number().int().min(0, '가격은 0 이상이어야 합니다'),
        status: z.enum(['VISIBLE', 'HIDDEN', 'SOLD_OUT']).default('VISIBLE'),
        displayOrder: z.number().int().nullish(),
        baseCapacity: z
          .number()
          .int()
          .positive('기준인원은 1명 이상이어야 합니다'),
        maxCapacity: z
          .number()
          .int()
          .positive('최대인원은 1명 이상이어야 합니다'),
        checkInTime: z
          .string()
          .regex(TIME_FORMAT_REGEX, TIME_FORMAT_ERROR_MESSAGE_KO)
          .transform(normalizeTime),
        checkOutTime: z
          .string()
          .regex(TIME_FORMAT_REGEX, TIME_FORMAT_ERROR_MESSAGE_KO)
          .transform(normalizeTime),
        bedTypes: z.array(z.string()).default([]),
        tags: z.array(z.string()).default([]),
        hotelOptions: z
          .array(
            z.object({
              id: z.number().int().positive().nullish(),
              name: z.string().min(1, '옵션명은 필수입니다'),
              priceByDate: z
                .record(z.string(), z.number().int().nonnegative())
                .default({}),
              anotherPriceByDate: z
                .record(
                  z.string(),
                  z.object({
                    supplyPrice: z.number().int().nonnegative(),
                    commission: z.number().int().nonnegative(),
                  })
                )
                .default({}),
            })
          )
          .default([]),
        hotelSkus: z
          .array(
            z.object({
              checkInDate: z
                .string()
                .regex(
                  /^\d{4}-\d{2}-\d{2}$/,
                  '날짜는 YYYY-MM-DD 형식이어야 합니다'
                ),
              quantity: z.number().int().min(0, '재고는 0 이상이어야 합니다'),
            })
          )
          .default([]),
      }),
      // Delivery Product
      z.object({
        type: z.literal('DELIVERY'),
        name: z.string().min(1, '상품명은 필수입니다'),
        brandId: z.number().int().positive('브랜드를 선택해주세요'),
        productTemplateId: z.number().int().positive().nullish(),
        campaignId: z.number().int().positive().nullish(),
        categoryIds: z.array(z.number().int().positive()).default([]),
        thumbnailUrls: z.array(z.string().url()).default([]),
        description: z.string().default(''),
        detailContent: z.string().default(''),
        useCalendar: z.boolean().default(false),
        useStock: z.boolean().default(false),
        useOptions: z.boolean().default(false),
        price: z.number().int().min(0, '가격은 0 이상이어야 합니다'),
        status: z.enum(['VISIBLE', 'HIDDEN', 'SOLD_OUT']).default('VISIBLE'),
        displayOrder: z.number().int().nullish(),
        delivery: z.object({
          deliveryFeeType: z.enum(['FREE', 'PAID', 'CONDITIONAL_FREE']),
          deliveryFee: z.number().int().nonnegative().default(0),
          freeDeliveryMinAmount: z.number().int().nonnegative().default(0),
          returnDeliveryFee: z.number().int().nonnegative().default(0),
          exchangeDeliveryFee: z.number().int().nonnegative().default(0),
          remoteAreaExtraFee: z.number().int().nonnegative().default(0),
          jejuExtraFee: z.number().int().nonnegative().default(0),
          isJejuRestricted: z.boolean().default(false),
          isRemoteIslandRestricted: z.boolean().default(false),
        }),
        exchangeReturnInfo: z.string().default(''),
        productInfoNotice: z.string().default(''),
      }),
      // ETicket Product
      z.object({
        type: z.literal('E-TICKET'),
        name: z.string().min(1, '상품명은 필수입니다'),
        brandId: z.number().int().positive('브랜드를 선택해주세요'),
        productTemplateId: z.number().int().positive().nullish(),
        campaignId: z.number().int().positive().nullish(),
        categoryIds: z.array(z.number().int().positive()).default([]),
        thumbnailUrls: z.array(z.string().url()).default([]),
        description: z.string().default(''),
        detailContent: z.string().default(''),
        useCalendar: z.boolean().default(false),
        useStock: z.boolean().default(false),
        useOptions: z.boolean().default(false),
        price: z.number().int().min(0, '가격은 0 이상이어야 합니다'),
        status: z.enum(['VISIBLE', 'HIDDEN', 'SOLD_OUT']).default('VISIBLE'),
        displayOrder: z.number().int().nullish(),
      }),
    ])).output(z.object({
      id: z.number(),
      type: z.enum(['HOTEL', 'E-TICKET', 'DELIVERY']),
      name: z.string(),
      message: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure.input(z.discriminatedUnion('type', [
      // Hotel Product Update
      z.object({
        type: z.literal('HOTEL'),
        id: z.number().int().positive('유효한 ID를 입력해주세요'),
        name: z.string().min(1, '상품명은 필수입니다'),
        brandId: z.number().int().positive('브랜드를 선택해주세요'),
        productTemplateId: z.number().int().positive().nullish(),
        campaignId: z.number().int().positive().nullish(),
        categoryIds: z.array(z.number().int().positive()).default([]),
        thumbnailUrls: z.array(z.string().url()).default([]),
        description: z.string().default(''),
        detailContent: z.string().default(''),
        useCalendar: z.literal(true),
        useStock: z.boolean().default(false),
        useOptions: z.boolean().default(false),
        price: z.number().int().min(0, '가격은 0 이상이어야 합니다'),
        status: z.enum(['VISIBLE', 'HIDDEN', 'SOLD_OUT']).default('VISIBLE'),
        displayOrder: z.number().int().nullish(),
        baseCapacity: z
          .number()
          .int()
          .positive('기준인원은 1명 이상이어야 합니다'),
        maxCapacity: z
          .number()
          .int()
          .positive('최대인원은 1명 이상이어야 합니다'),
        checkInTime: z
          .string()
          .regex(TIME_FORMAT_REGEX, TIME_FORMAT_ERROR_MESSAGE_KO)
          .transform(normalizeTime),
        checkOutTime: z
          .string()
          .regex(TIME_FORMAT_REGEX, TIME_FORMAT_ERROR_MESSAGE_KO)
          .transform(normalizeTime),
        bedTypes: z.array(z.string()).default([]),
        tags: z.array(z.string()).default([]),
        hotelOptions: z
          .array(
            z.object({
              id: z.number().int().positive().nullish(),
              name: z.string().min(1, '옵션명은 필수입니다'),
              priceByDate: z
                .record(z.string(), z.number().int().nonnegative())
                .default({}),
              anotherPriceByDate: z
                .record(
                  z.string(),
                  z.object({
                    supplyPrice: z.number().int().nonnegative(),
                    commission: z.number().int().nonnegative(),
                  })
                )
                .default({}),
            })
          )
          .default([]),
        hotelSkus: z
          .array(
            z.object({
              checkInDate: z
                .string()
                .regex(
                  /^\d{4}-\d{2}-\d{2}$/,
                  '날짜는 YYYY-MM-DD 형식이어야 합니다'
                ),
              quantity: z.number().int().min(0, '재고는 0 이상이어야 합니다'),
            })
          )
          .default([]),
      }),
      // Delivery Product Update
      z.object({
        type: z.literal('DELIVERY'),
        id: z.number().int().positive('유효한 ID를 입력해주세요'),
        name: z.string().min(1, '상품명은 필수입니다'),
        brandId: z.number().int().positive('브랜드를 선택해주세요'),
        productTemplateId: z.number().int().positive().nullish(),
        campaignId: z.number().int().positive().nullish(),
        categoryIds: z.array(z.number().int().positive()).default([]),
        thumbnailUrls: z.array(z.string().url()).default([]),
        description: z.string().default(''),
        detailContent: z.string().default(''),
        useCalendar: z.boolean().default(false),
        useStock: z.boolean().default(false),
        useOptions: z.boolean().default(false),
        price: z.number().int().min(0, '가격은 0 이상이어야 합니다'),
        status: z.enum(['VISIBLE', 'HIDDEN', 'SOLD_OUT']).default('VISIBLE'),
        displayOrder: z.number().int().nullish(),
        delivery: z.object({
          deliveryFeeType: z.enum(['FREE', 'PAID', 'CONDITIONAL_FREE']),
          deliveryFee: z.number().int().nonnegative().default(0),
          freeDeliveryMinAmount: z.number().int().nonnegative().default(0),
          returnDeliveryFee: z.number().int().nonnegative().default(0),
          exchangeDeliveryFee: z.number().int().nonnegative().default(0),
          remoteAreaExtraFee: z.number().int().nonnegative().default(0),
          jejuExtraFee: z.number().int().nonnegative().default(0),
          isJejuRestricted: z.boolean().default(false),
          isRemoteIslandRestricted: z.boolean().default(false),
        }),
        exchangeReturnInfo: z.string().default(''),
        productInfoNotice: z.string().default(''),
      }),
      // ETicket Product Update
      z.object({
        type: z.literal('E-TICKET'),
        id: z.number().int().positive('유효한 ID를 입력해주세요'),
        name: z.string().min(1, '상품명은 필수입니다'),
        brandId: z.number().int().positive('브랜드를 선택해주세요'),
        productTemplateId: z.number().int().positive().nullish(),
        campaignId: z.number().int().positive().nullish(),
        categoryIds: z.array(z.number().int().positive()).default([]),
        thumbnailUrls: z.array(z.string().url()).default([]),
        description: z.string().default(''),
        detailContent: z.string().default(''),
        useCalendar: z.boolean().default(false),
        useStock: z.boolean().default(false),
        useOptions: z.boolean().default(false),
        price: z.number().int().min(0, '가격은 0 이상이어야 합니다'),
        status: z.enum(['VISIBLE', 'HIDDEN', 'SOLD_OUT']).default('VISIBLE'),
        displayOrder: z.number().int().nullish(),
      }),
    ])).output(z.object({
      id: z.number(),
      name: z.string(),
      message: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure.input(z.object({
      id: z.number().int().positive('유효한 ID를 입력해주세요'),
    })).output(z.object({
      id: z.number(),
      message: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  backofficeOrder: t.router({
    findAll: publicProcedure.input(z.object({
      type: z.enum(['HOTEL', 'E-TICKET', 'DELIVERY']).nullish(),
      status: z.enum([
        'PENDING',
        'PAID',
        'PENDING_RESERVATION',
        'RESERVATION_CONFIRMED',
        'COMPLETED',
        'PREPARING_SHIPMENT',
        'SHIPPING',
        'DELIVERED',
        'PURCHASE_CONFIRMED',
        'CANCEL_REQUESTED',
        'CANCELLED',
        'RETURN_REQUESTED',
        'RETURNING',
        'RETURNED',
      ]).nullish(),
      periodFilterType: z.enum([
        'PAYMENT_DATE',
        'ORDER_DATE',
        'USAGE_DATE',
      ]).nullish(),
      startDate: z.string().nullish(),
      endDate: z.string().nullish(),
      campaignId: z.number().int().positive().nullish(),
      influencerIds: z.array(z.number().int().positive()).nullish(),
      productId: z.number().int().positive().nullish(),
      searchQuery: z.string().nullish(),
    }).extend({
      // 페이지네이션
      page: z.number().int().min(1).default(1),
      limit: z.number().int().positive().default(50),
      orderBy: z.string().default('createdAt'),
      order: z.enum(['ASC', 'DESC']).default('DESC'),
    }).nullish().default({})).output(z.object({
      data: z.array(z.object({
        id: z.number(),
        orderNumber: z.string(),
        type: z.enum(['HOTEL', 'E-TICKET', 'DELIVERY']),
        status: z.enum([
          'PENDING',
          'PAID',
          'PENDING_RESERVATION',
          'RESERVATION_CONFIRMED',
          'COMPLETED',
          'PREPARING_SHIPMENT',
          'SHIPPING',
          'DELIVERED',
          'PURCHASE_CONFIRMED',
          'CANCEL_REQUESTED',
          'CANCELLED',
          'RETURN_REQUESTED',
          'RETURNING',
          'RETURNED',
        ]),
        customerName: z.string(),
        customerPhone: z.string(),
        totalAmount: z.number(),

        // 관계 데이터
        productId: z.number(),
        productName: z.string(),
        campaignId: z.number(),
        campaignName: z.string(),
        influencerId: z.number(),
        influencerName: z.string(),

        // 호텔 전용 필드 (nullable)
        checkInDate: z.string().nullish(),
        checkOutDate: z.string().nullish(),
        hotelOptionName: z.string().nullish(),

        // 타임스탬프
        createdAt: z.date(),
        updatedAt: z.date(),
      })),
      total: z.number(),
      page: z.number(),
      limit: z.number(),
      totalPages: z.number(),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getStatusCounts: publicProcedure.input(z.object({
      type: z.enum(['HOTEL', 'E-TICKET', 'DELIVERY']).nullish(),
      status: z.enum([
        'PENDING',
        'PAID',
        'PENDING_RESERVATION',
        'RESERVATION_CONFIRMED',
        'COMPLETED',
        'PREPARING_SHIPMENT',
        'SHIPPING',
        'DELIVERED',
        'PURCHASE_CONFIRMED',
        'CANCEL_REQUESTED',
        'CANCELLED',
        'RETURN_REQUESTED',
        'RETURNING',
        'RETURNED',
      ]).nullish(),
      periodFilterType: z.enum([
        'PAYMENT_DATE',
        'ORDER_DATE',
        'USAGE_DATE',
      ]).nullish(),
      startDate: z.string().nullish(),
      endDate: z.string().nullish(),
      campaignId: z.number().int().positive().nullish(),
      influencerIds: z.array(z.number().int().positive()).nullish(),
      productId: z.number().int().positive().nullish(),
      searchQuery: z.string().nullish(),
    }).nullish().default({})).output(z.object({
      ALL: z.number(),
      PENDING: z.number(),
      PAID: z.number(),
      PENDING_RESERVATION: z.number(),
      RESERVATION_CONFIRMED: z.number(),
      COMPLETED: z.number(),
      PREPARING_SHIPMENT: z.number(),
      SHIPPING: z.number(),
      DELIVERED: z.number(),
      PURCHASE_CONFIRMED: z.number(),
      CANCEL_REQUESTED: z.number(),
      CANCELLED: z.number(),
      RETURN_REQUESTED: z.number(),
      RETURNING: z.number(),
      RETURNED: z.number(),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getFilterOptions: publicProcedure.output(z.object({
      campaigns: z.array(
        z.object({
          id: z.number(),
          name: z.string(),
        })
      ),
      influencers: z.array(
        z.object({
          id: z.number(),
          name: z.string(),
        })
      ),
      products: z.array(
        z.object({
          id: z.number(),
          name: z.string(),
        })
      ),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findById: publicProcedure.input(z.object({
      id: z.number().int().positive(),
    })).output(z.object({
      id: z.number(),
      orderNumber: z.string(),
      type: z.enum(['HOTEL', 'E-TICKET', 'DELIVERY']),
      status: z.enum([
        'PENDING',
        'PAID',
        'PENDING_RESERVATION',
        'RESERVATION_CONFIRMED',
        'COMPLETED',
        'PREPARING_SHIPMENT',
        'SHIPPING',
        'DELIVERED',
        'PURCHASE_CONFIRMED',
        'CANCEL_REQUESTED',
        'CANCELLED',
        'RETURN_REQUESTED',
        'RETURNING',
        'RETURNED',
      ]),
      statusLabel: z.string(),
      statusDate: z.date().nullish(),

      // 캠페인/인플루언서 정보
      campaignId: z.number(),
      campaignName: z.string(),
      influencerId: z.number(),
      influencerName: z.string(),

      // 주문 일시
      orderedAt: z.date(),

      // 주문 아이템 목록
      items: z.array(z.object({
        id: z.number(),
        productName: z.string(),
        optionName: z.string(),
        checkInDate: z.string().nullish(),
        checkOutDate: z.string().nullish(),
        amount: z.number(),
      })),

      // 결제 정보
      payment: z.object({
        paymentMethod: z.string(),
        productAmount: z.number(),
        refundAmount: z.number(),
        totalAmount: z.number(),
        paidAt: z.date().nullish(),
      }),

      // 회원 정보
      member: z.object({
        name: z.string(),
        phone: z.string(),
      }),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    updateStatus: publicProcedure.input(z.object({
      orderId: z.number().int().positive(),
      status: z.enum([
        'PENDING',
        'PAID',
        'PENDING_RESERVATION',
        'RESERVATION_CONFIRMED',
        'COMPLETED',
        'PREPARING_SHIPMENT',
        'SHIPPING',
        'DELIVERED',
        'PURCHASE_CONFIRMED',
        'CANCEL_REQUESTED',
        'CANCELLED',
        'RETURN_REQUESTED',
        'RETURNING',
        'RETURNED',
      ]),
    })).output(z.object({
      success: z.boolean(),
      orderId: z.number(),
      previousStatus: z.enum([
        'PENDING',
        'PAID',
        'PENDING_RESERVATION',
        'RESERVATION_CONFIRMED',
        'COMPLETED',
        'PREPARING_SHIPMENT',
        'SHIPPING',
        'DELIVERED',
        'PURCHASE_CONFIRMED',
        'CANCEL_REQUESTED',
        'CANCELLED',
        'RETURN_REQUESTED',
        'RETURNING',
        'RETURNED',
      ]),
      newStatus: z.enum([
        'PENDING',
        'PAID',
        'PENDING_RESERVATION',
        'RESERVATION_CONFIRMED',
        'COMPLETED',
        'PREPARING_SHIPMENT',
        'SHIPPING',
        'DELIVERED',
        'PURCHASE_CONFIRMED',
        'CANCEL_REQUESTED',
        'CANCELLED',
        'RETURN_REQUESTED',
        'RETURNING',
        'RETURNED',
      ]),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    exportToExcel: publicProcedure.input(z.object({
      type: z.enum(['HOTEL', 'E-TICKET', 'DELIVERY']).nullish(),
      status: z.enum([
        'PENDING',
        'PAID',
        'PENDING_RESERVATION',
        'RESERVATION_CONFIRMED',
        'COMPLETED',
        'PREPARING_SHIPMENT',
        'SHIPPING',
        'DELIVERED',
        'PURCHASE_CONFIRMED',
        'CANCEL_REQUESTED',
        'CANCELLED',
        'RETURN_REQUESTED',
        'RETURNING',
        'RETURNED',
      ]).nullish(),
      periodFilterType: z.enum([
        'PAYMENT_DATE',
        'ORDER_DATE',
        'USAGE_DATE',
      ]).nullish(),
      startDate: z.string().nullish(),
      endDate: z.string().nullish(),
      campaignId: z.number().int().positive().nullish(),
      influencerIds: z.array(z.number().int().positive()).nullish(),
      productId: z.number().int().positive().nullish(),
      searchQuery: z.string().nullish(),
    }).nullish().default({})).output(z.object({
      downloadUrl: z.string(),
      fileName: z.string(),
      totalCount: z.number(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  backofficeInfluencer: t.router({
    findAll: publicProcedure.input(z.object({
      page: z.number().min(1).default(1),
      limit: z.number().min(1).max(100).default(50),
      ids: z.array(z.number().int().positive()).nullish(),
    })).output(z.object({
      data: z.array(
        z.object({
          id: z.number(),
          name: z.string(),
          slug: z.string(),
          email: z.string().nullish(),
          phoneNumber: z.string().nullish(),
          thumbnail: z.string().nullish(),
          createdAt: z.date(),
        })
      ),
      total: z.number(),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure.input(z.object({
      name: z.string().min(1, '인플루언서명은 필수입니다'),
      slug: z
        .string()
        .min(1, '샵 URL은 필수입니다')
        .max(50, '샵 URL은 50자 이내로 입력해주세요')
        .regex(
          /^[a-z0-9_-]+$/,
          '샵 URL은 영문 소문자, 숫자, 하이픈(-), 언더스코어(_)만 사용 가능합니다'
        ),
      email: z.string().email('유효한 이메일을 입력해주세요').nullish(),
      phoneNumber: z.string().nullish(),
      thumbnail: z.string().nullish(),
      businessInfo: z.object({
        type: z.enum(BUSINESS_TYPE_ENUM_VALUE).nullish(),
        name: z.string().nullish(),
        licenseNumber: z.string().nullish(),
        ceoName: z.string().nullish(),
        licenseFileUrl: z.string().nullish(),
      }).nullish(),
      bankInfo: z.object({
        name: z.string().nullish(),
        accountNumber: z.string().nullish(),
        accountHolder: z.string().nullish(),
      }).nullish(),
      socialMedias: z
        .array(
          z.object({
            platform: socialMediaPlatformEnumSchema,
            url: z.string().url('유효한 URL을 입력해주세요'),
          })
        )
        .min(1, '최소 1개 이상의 소셜미디어가 필요합니다'),
    })).output(z.object({
      id: z.number(),
      name: z.string(),
      slug: z.string(),
      email: z.string().email().nullish(),
      phoneNumber: z.string().nullish(),
      thumbnail: z.string().nullish(),
      businessInfo: businessInfoSchema.nullish(),
      bankInfo: bankInfoSchema.nullish(),
      socialMedias: z.array(z.object({
        id: z.number().optional(),
        platform: z.enum(
          [
            'INSTAGRAM',
            'TIKTOK',
            'YOUTUBE',
            'FACEBOOK',
            'TWITTER',
            'OTHER',
          ] as const
        ),
        url: z.string().url('유효한 URL을 입력해주세요'),
      })),
      createdAt: z.date(),
      updatedAt: z.date(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findById: publicProcedure.input(z.object({
      id: z.number(),
    })).output(z.object({
      id: z.number(),
      name: z.string(),
      slug: z.string(),
      email: z.string().email().nullish(),
      phoneNumber: z.string().nullish(),
      thumbnail: z.string().nullish(),
      businessInfo: businessInfoSchema.nullish(),
      bankInfo: bankInfoSchema.nullish(),
      socialMedias: z.array(z.object({
        id: z.number().optional(),
        platform: z.enum(
          [
            'INSTAGRAM',
            'TIKTOK',
            'YOUTUBE',
            'FACEBOOK',
            'TWITTER',
            'OTHER',
          ] as const
        ),
        url: z.string().url('유효한 URL을 입력해주세요'),
      })),
      createdAt: z.date(),
      updatedAt: z.date(),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure.input(z.object({
      id: z.number(),
      name: z.string().min(1, '인플루언서명은 필수입니다'),
      slug: z
        .string()
        .min(1, '샵 URL은 필수입니다')
        .max(50, '샵 URL은 50자 이내로 입력해주세요')
        .regex(
          /^[a-z0-9_-]+$/,
          '샵 URL은 영문 소문자, 숫자, 하이픈(-), 언더스코어(_)만 사용 가능합니다'
        ),
      email: z.string().email('유효한 이메일을 입력해주세요').nullish(),
      phoneNumber: z.string().nullish(),
      thumbnail: z.string().nullish(),
      businessInfo: z.object({
        type: z.enum(BUSINESS_TYPE_ENUM_VALUE).nullish(),
        name: z.string().nullish(),
        licenseNumber: z.string().nullish(),
        ceoName: z.string().nullish(),
        licenseFileUrl: z.string().nullish(),
      }).nullish(),
      bankInfo: z.object({
        name: z.string().nullish(),
        accountNumber: z.string().nullish(),
        accountHolder: z.string().nullish(),
      }).nullish(),
      socialMedias: z
        .array(
          z.object({
            platform: socialMediaPlatformEnumSchema,
            url: z.string().url('유효한 URL을 입력해주세요'),
          })
        )
        .min(1, '최소 1개 이상의 소셜미디어가 필요합니다'),
    })).output(z.object({
      id: z.number(),
      name: z.string(),
      slug: z.string(),
      email: z.string().email().nullish(),
      phoneNumber: z.string().nullish(),
      thumbnail: z.string().nullish(),
      businessInfo: businessInfoSchema.nullish(),
      bankInfo: bankInfoSchema.nullish(),
      socialMedias: z.array(z.object({
        id: z.number().optional(),
        platform: z.enum(
          [
            'INSTAGRAM',
            'TIKTOK',
            'YOUTUBE',
            'FACEBOOK',
            'TWITTER',
            'OTHER',
          ] as const
        ),
        url: z.string().url('유효한 URL을 입력해주세요'),
      })),
      createdAt: z.date(),
      updatedAt: z.date(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  backofficeCategory: t.router({
    create: publicProcedure.input(z.object({
      name: z.string().min(1, '카테고리 이름은 필수입니다'),
      productType: z.enum(PRODUCT_TYPE_ENUM_VALUE),
      parentId: z.number().nullish(),
    })).output(z.object({
      id: z.number(),
      name: z.string(),
      productType: z.string(),
      parentId: z.number().nullish(),
      level: z.number(),
      createdAt: z.date(),
      updatedAt: z.date(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findAll: publicProcedure.input(z
      .object({
        productType: z.enum(PRODUCT_TYPE_ENUM_VALUE).optional(),
      })
      .optional()).output(z.array(
        z.object({
          id: z.number(),
          name: z.string(),
          productType: z.string(),
          parentId: z.number().nullish(),
          level: z.number(),
          createdAt: z.date(),
          updatedAt: z.date(),
        })
      )).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  backofficeCampaign: t.router({
    findAll: publicProcedure.output(z.array(z.object({
      id: z.number(),
      title: z.string(),
      startAt: z.date(),
      endAt: z.date(),
      description: z.string().nullish(),
      thumbnail: z.string().nullish(),
      createdAt: z.date(),
      updatedAt: z.date(),
    }))).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findById: publicProcedure.input(z.object({
      id: z.number(),
    })).output(z.object({
      id: z.number(),
      title: z.string(),
      startAt: z.date(),
      endAt: z.date(),
      description: z.string().nullish(),
      thumbnail: z.string().nullish(),
      createdAt: z.date(),
      updatedAt: z.date(),
    }).extend({
      products: z.array(z.object({
        // Product 정보 (flat)
        id: z.number(),
        name: z.string(),
        thumbnailUrls: z.array(z.string()),
        brand: z.object({
          id: z.number(),
          name: z.string(),
        }),
        categories: z.array(
          z.object({
            id: z.number(),
            name: z.string(),
          })
        ),
        createdAt: z.date(),
        updatedAt: z.date(),
        // CampaignProduct 메타데이터
        campaignProductId: z.number(),
        status: z.enum([
          'VISIBLE',
          'HIDDEN',
          'SOLD_OUT',
        ] as const),
      })),
      influencers: z.array(z.object({
        campaignInfluencerId: z.string(), // composite key: `${campaignId}_${influencerId}`
        influencerId: z.number(),
        name: z.string(),
        slug: z.string().nullable(),
        thumbnail: z.string().nullable(),
        periodType: z.enum(
          ['DEFAULT', 'CUSTOM'] as const
        ),
        startAt: z.date().nullable(),
        endAt: z.date().nullable(),
        feeType: z.enum(['NONE', 'CUSTOM'] as const),
        fee: z.number().nullable(),
        status: z.enum([
          'VISIBLE',
          'HIDDEN',
          'SOLD_OUT',
        ] as const),
        // 인플루언서별 상품 목록
        products: z.array(z.object({
          campaignInfluencerProductId: z.number(),
          productId: z.number(),
          status: z.enum([
            'VISIBLE',
            'HIDDEN',
            'SOLD_OUT',
          ] as const),
          useCustomCommission: z.boolean(),
          hotelOptions: z.array(z.object({
            campaignInfluencerHotelOptionId: z.number(),
            hotelOptionId: z.number(),
            commissionByDate: z.record(z.string(), z.number()),
          })),
        })),
      })),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure.input(z.object({
      title: z.string().min(1, '캠페인명은 필수입니다'),
      startAt: z.coerce.date(),
      endAt: z.coerce.date(),
      description: z.string().nullish(),
      thumbnail: z.string().nullish(),
      // 상품 목록 (선택)
      products: z.array(campaignProductInputSchema).default([]),
      // 인플루언서 목록 (선택)
      influencers: z.array(campaignInfluencerInputSchema).default([]),
    })).output(z.object({
      id: z.number(),
      title: z.string(),
      startAt: z.date(),
      endAt: z.date(),
      description: z.string().nullish(),
      thumbnail: z.string().nullish(),
      createdAt: z.date(),
      updatedAt: z.date(),
    }).extend({
      products: z.array(z.object({
        // Product 정보 (flat)
        id: z.number(),
        name: z.string(),
        thumbnailUrls: z.array(z.string()),
        brand: z.object({
          id: z.number(),
          name: z.string(),
        }),
        categories: z.array(
          z.object({
            id: z.number(),
            name: z.string(),
          })
        ),
        createdAt: z.date(),
        updatedAt: z.date(),
        // CampaignProduct 메타데이터
        campaignProductId: z.number(),
        status: z.enum([
          'VISIBLE',
          'HIDDEN',
          'SOLD_OUT',
        ] as const),
      })),
      influencers: z.array(z.object({
        campaignInfluencerId: z.string(), // composite key: `${campaignId}_${influencerId}`
        influencerId: z.number(),
        name: z.string(),
        slug: z.string().nullable(),
        thumbnail: z.string().nullable(),
        periodType: z.enum(
          ['DEFAULT', 'CUSTOM'] as const
        ),
        startAt: z.date().nullable(),
        endAt: z.date().nullable(),
        feeType: z.enum(['NONE', 'CUSTOM'] as const),
        fee: z.number().nullable(),
        status: z.enum([
          'VISIBLE',
          'HIDDEN',
          'SOLD_OUT',
        ] as const),
        // 인플루언서별 상품 목록
        products: z.array(z.object({
          campaignInfluencerProductId: z.number(),
          productId: z.number(),
          status: z.enum([
            'VISIBLE',
            'HIDDEN',
            'SOLD_OUT',
          ] as const),
          useCustomCommission: z.boolean(),
          hotelOptions: z.array(z.object({
            campaignInfluencerHotelOptionId: z.number(),
            hotelOptionId: z.number(),
            commissionByDate: z.record(z.string(), z.number()),
          })),
        })),
      })),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure.input(z.object({
      title: z.string().min(1, '캠페인명은 필수입니다'),
      startAt: z.coerce.date(),
      endAt: z.coerce.date(),
      description: z.string().nullish(),
      thumbnail: z.string().nullish(),
      // 상품 목록 (선택)
      products: z.array(campaignProductInputSchema).default([]),
      // 인플루언서 목록 (선택)
      influencers: z.array(campaignInfluencerInputSchema).default([]),
    }).extend({
      id: z.number(),
    })).output(z.object({
      id: z.number(),
      title: z.string(),
      startAt: z.date(),
      endAt: z.date(),
      description: z.string().nullish(),
      thumbnail: z.string().nullish(),
      createdAt: z.date(),
      updatedAt: z.date(),
    }).extend({
      products: z.array(z.object({
        // Product 정보 (flat)
        id: z.number(),
        name: z.string(),
        thumbnailUrls: z.array(z.string()),
        brand: z.object({
          id: z.number(),
          name: z.string(),
        }),
        categories: z.array(
          z.object({
            id: z.number(),
            name: z.string(),
          })
        ),
        createdAt: z.date(),
        updatedAt: z.date(),
        // CampaignProduct 메타데이터
        campaignProductId: z.number(),
        status: z.enum([
          'VISIBLE',
          'HIDDEN',
          'SOLD_OUT',
        ] as const),
      })),
      influencers: z.array(z.object({
        campaignInfluencerId: z.string(), // composite key: `${campaignId}_${influencerId}`
        influencerId: z.number(),
        name: z.string(),
        slug: z.string().nullable(),
        thumbnail: z.string().nullable(),
        periodType: z.enum(
          ['DEFAULT', 'CUSTOM'] as const
        ),
        startAt: z.date().nullable(),
        endAt: z.date().nullable(),
        feeType: z.enum(['NONE', 'CUSTOM'] as const),
        fee: z.number().nullable(),
        status: z.enum([
          'VISIBLE',
          'HIDDEN',
          'SOLD_OUT',
        ] as const),
        // 인플루언서별 상품 목록
        products: z.array(z.object({
          campaignInfluencerProductId: z.number(),
          productId: z.number(),
          status: z.enum([
            'VISIBLE',
            'HIDDEN',
            'SOLD_OUT',
          ] as const),
          useCustomCommission: z.boolean(),
          hotelOptions: z.array(z.object({
            campaignInfluencerHotelOptionId: z.number(),
            hotelOptionId: z.number(),
            commissionByDate: z.record(z.string(), z.number()),
          })),
        })),
      })),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure.input(z.object({
      id: z.number(),
    })).output(z.object({ success: z.boolean() })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  backofficeBrand: t.router({
    register: publicProcedure.input(z.object({
      name: z.string().min(1, 'Brand name is required'),
      email: z.string().email().nullish(),
      phoneNumber: z.string().nullish(),
      businessInfo: z.object({
        type: z.enum([
          'CORPORATION',
          'SOLE_PROPRIETOR',
          'INDIVIDUAL',
        ] as const).nullish(),
        name: z.string().nullish(),
        licenseNumber: z.string().nullish(),
        ceoName: z.string().nullish(),
        licenseFileUrl: z.string().nullish(),
      }).nullish(),
      bankInfo: z.object({
        name: z.string().nullish(),
        accountNumber: z.string().nullish(),
        accountHolder: z.string().nullish(),
      }).nullish(),
    })).output(z.object({
      id: z.number(),
      name: z.string(),
      email: z.string().email().nullish(),
      phoneNumber: z.string().nullish(),
      businessInfo: z.object({
        type: z.enum([
          'CORPORATION',
          'SOLE_PROPRIETOR',
          'INDIVIDUAL',
        ] as const).nullish(),
        name: z.string().nullish(),
        licenseNumber: z.string().nullish(),
        ceoName: z.string().nullish(),
        licenseFileUrl: z.string().nullish(),
      }).nullish(),
      bankInfo: z.object({
        name: z.string().nullish(),
        accountNumber: z.string().nullish(),
        accountHolder: z.string().nullish(),
      }).nullish(),
      brandManagers: z.array(brandManagerSchema).optional(),
      createdAt: z.date(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findAll: publicProcedure.output(z.array(z.object({
      id: z.number(),
      name: z.string(),
      email: z.string().email().nullish(),
      phoneNumber: z.string().nullish(),
      businessInfo: z.object({
        type: z.enum([
          'CORPORATION',
          'SOLE_PROPRIETOR',
          'INDIVIDUAL',
        ] as const).nullish(),
        name: z.string().nullish(),
        licenseNumber: z.string().nullish(),
        ceoName: z.string().nullish(),
        licenseFileUrl: z.string().nullish(),
      }).nullish(),
      bankInfo: z.object({
        name: z.string().nullish(),
        accountNumber: z.string().nullish(),
        accountHolder: z.string().nullish(),
      }).nullish(),
      brandManagers: z.array(brandManagerSchema).optional(),
      createdAt: z.date(),
    }))).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findById: publicProcedure.input(z.object({
      id: z.number(),
    })).output(z.object({
      id: z.number(),
      name: z.string(),
      email: z.string().email().nullish(),
      phoneNumber: z.string().nullish(),
      businessInfo: z.object({
        type: z.enum([
          'CORPORATION',
          'SOLE_PROPRIETOR',
          'INDIVIDUAL',
        ] as const).nullish(),
        name: z.string().nullish(),
        licenseNumber: z.string().nullish(),
        ceoName: z.string().nullish(),
        licenseFileUrl: z.string().nullish(),
      }).nullish(),
      bankInfo: z.object({
        name: z.string().nullish(),
        accountNumber: z.string().nullish(),
        accountHolder: z.string().nullish(),
      }).nullish(),
      brandManagers: z.array(brandManagerSchema).optional(),
      createdAt: z.date(),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure.input(z.object({
      name: z.string().min(1, 'Brand name is required'),
      email: z.string().email().nullish(),
      phoneNumber: z.string().nullish(),
      businessInfo: z.object({
        type: z.enum([
          'CORPORATION',
          'SOLE_PROPRIETOR',
          'INDIVIDUAL',
        ] as const).nullish(),
        name: z.string().nullish(),
        licenseNumber: z.string().nullish(),
        ceoName: z.string().nullish(),
        licenseFileUrl: z.string().nullish(),
      }).nullish(),
      bankInfo: z.object({
        name: z.string().nullish(),
        accountNumber: z.string().nullish(),
        accountHolder: z.string().nullish(),
      }).nullish(),
    }).extend({
      id: z.number(),
    })).output(z.object({
      id: z.number(),
      name: z.string(),
      email: z.string().email().nullish(),
      phoneNumber: z.string().nullish(),
      businessInfo: z.object({
        type: z.enum([
          'CORPORATION',
          'SOLE_PROPRIETOR',
          'INDIVIDUAL',
        ] as const).nullish(),
        name: z.string().nullish(),
        licenseNumber: z.string().nullish(),
        ceoName: z.string().nullish(),
        licenseFileUrl: z.string().nullish(),
      }).nullish(),
      bankInfo: z.object({
        name: z.string().nullish(),
        accountNumber: z.string().nullish(),
        accountHolder: z.string().nullish(),
      }).nullish(),
      brandManagers: z.array(brandManagerSchema).optional(),
      createdAt: z.date(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    delete: publicProcedure.input(z.object({
      id: z.number(),
    })).output(z.object({ success: z.boolean() })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  backofficeAuth: t.router({
    register: publicProcedure.input(z.object({
      email: z.string().email('이메일 형식이 아닙니다.'),
      password: z.string().min(8, '비밀번호는 최소 8자 이상이어야 합니다.'),
      name: z.string().min(1, '이름은 필수입니다.'),
      phoneNumber: z.string().min(1, '전화번호는 필수입니다.'),
      role: z.enum([
        'ADMIN_SUPER',
        'ADMIN_STAFF',
        'PARTNER_SUPER',
        'PARTNER_STAFF',
      ] as const),
    })).output(z.object({
      message: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    login: publicProcedure.input(z.object({
      email: z.string().email('이메일 형식이 아닙니다.'),
      password: z.string(),
    })).output(z.object({
      accessToken: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    refresh: publicProcedure.output(z.object({
      accessToken: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    test: publicProcedure.output(z.object({
      message: z.string(),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  backofficeAdmin: t.router({
    create: publicProcedure.input(z.object({
      email: z.string().email('올바른 이메일 형식이 아닙니다'),
      password: z.string().min(6, '비밀번호는 최소 6자 이상이어야 합니다'),
      name: z.string().min(1, '이름은 필수입니다'),
      phoneNumber: z.string().min(1, '전화번호는 필수입니다'),
      role: z.enum([
        'ADMIN_SUPER',
        'ADMIN_STAFF',
        'PARTNER_SUPER',
        'PARTNER_STAFF',
      ] as const),
    })).output(z.object({
      id: z.number(),
      email: z.string().email(),
      name: z.string(),
      phoneNumber: z.string(),
      role: z.enum([
        'ADMIN_SUPER',
        'ADMIN_STAFF',
        'PARTNER_SUPER',
        'PARTNER_STAFF',
      ] as const),
      createdAt: z.date(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findAll: publicProcedure.output(z.array(z.object({
      id: z.number(),
      email: z.string().email(),
      name: z.string(),
      role: z.enum([
        'ADMIN_SUPER',
        'ADMIN_STAFF',
        'PARTNER_SUPER',
        'PARTNER_STAFF',
      ] as const),
    }))).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findById: publicProcedure.input(z.object({
      id: z.number(),
    })).output(z.object({
      id: z.number(),
      email: z.string().email(),
      name: z.string(),
      phoneNumber: z.string(),
      role: z.enum([
        'ADMIN_SUPER',
        'ADMIN_STAFF',
        'PARTNER_SUPER',
        'PARTNER_STAFF',
      ] as const),
      createdAt: z.date(),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    update: publicProcedure.input(z.object({
      id: z.number(),
      name: z.string().min(1, '이름은 필수입니다'),
      phoneNumber: z.string().min(1, '전화번호는 필수입니다'),
      role: z.enum([
        'ADMIN_SUPER',
        'ADMIN_STAFF',
        'PARTNER_SUPER',
        'PARTNER_STAFF',
      ] as const),
    })).output(z.object({
      id: z.number(),
      email: z.string().email(),
      name: z.string(),
      phoneNumber: z.string(),
      role: z.enum([
        'ADMIN_SUPER',
        'ADMIN_STAFF',
        'PARTNER_SUPER',
        'PARTNER_STAFF',
      ] as const),
      createdAt: z.date(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    updatePassword: publicProcedure.input(z.object({
      id: z.number(),
      newPassword: z.string().min(6, '비밀번호는 최소 6자 이상이어야 합니다'),
    })).output(z.object({
      success: z.boolean(),
      message: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  }),
  backofficeSettlement: t.router({
    findAll: publicProcedure.input(z.object({
      status: z.enum(['PENDING', 'COMPLETED']).nullish(),
      targetType: z.enum(['INFLUENCER', 'BRAND']).nullish(),
      campaignId: z.number().int().positive().nullish(),
      targetId: z.number().int().positive().nullish(),
      periodYear: z.number().int().positive().nullish(),
      periodMonth: z.number().int().min(1).max(12).nullish(),
      page: z.number().int().min(1).default(1),
      limit: z.number().int().positive().default(50),
    }).nullish().default({})).output(z.object({
      data: z.array(z.object({
        id: z.number(),
        targetType: z.enum(['INFLUENCER', 'BRAND']),
        targetId: z.number(),
        targetName: z.string(),
        periodYear: z.number(),
        periodMonth: z.number(),
        status: z.enum(['PENDING', 'COMPLETED']),
        scheduledAt: z.date(),
        completedAt: z.date().nullish(),
        totalSales: z.number(),
        totalQuantity: z.number(),
        totalAmount: z.number(),
        campaignNames: z.array(z.string()),
        createdAt: z.date(),
      })),
      total: z.number(),
      page: z.number(),
      limit: z.number(),
      totalPages: z.number(),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findInfluencerSettlementById: publicProcedure.input(z.object({
      id: z.number().int().positive(),
    })).output(z.object({
      id: z.number(),
      influencerId: z.number(),
      influencerName: z.string(),
      periodYear: z.number(),
      periodMonth: z.number(),
      status: z.enum(['PENDING', 'COMPLETED']),
      scheduledAt: z.date(),
      completedAt: z.date().nullish(),
      totalSales: z.number(),
      totalQuantity: z.number(),
      totalAmount: z.number(),
      campaignGroups: z.array(z.object({
        campaignId: z.number(),
        campaignName: z.string(),
        campaignPeriod: z.string(),
        products: z.array(z.object({
          productId: z.number(),
          productName: z.string(),
          optionName: z.string().nullish(),
          quantity: z.number(),
          sales: z.number(),
          settlementAmount: z.number(),
        })),
        subtotalQuantity: z.number(),
        subtotalSales: z.number(),
        subtotalAmount: z.number(),
      })),
      bankAccount: z.object({
        bankName: z.string().nullish(),
        accountNumber: z.string().nullish(),
        accountHolder: z.string().nullish(),
      }),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    findBrandSettlementById: publicProcedure.input(z.object({
      id: z.number().int().positive(),
    })).output(z.object({
      id: z.number(),
      brandId: z.number(),
      brandName: z.string(),
      periodYear: z.number(),
      periodMonth: z.number(),
      status: z.enum(['PENDING', 'COMPLETED']),
      scheduledAt: z.date(),
      completedAt: z.date().nullish(),
      totalSales: z.number(),
      totalQuantity: z.number(),
      totalAmount: z.number(),
      campaignGroups: z.array(z.object({
        campaignId: z.number(),
        campaignName: z.string(),
        campaignPeriod: z.string(),
        products: z.array(z.object({
          productId: z.number(),
          productName: z.string(),
          optionName: z.string().nullish(),
          quantity: z.number(),
          sales: z.number(),
          settlementAmount: z.number(),
        })),
        subtotalQuantity: z.number(),
        subtotalSales: z.number(),
        subtotalAmount: z.number(),
      })),
      bankAccount: z.object({
        bankName: z.string().nullish(),
        accountNumber: z.string().nullish(),
        accountHolder: z.string().nullish(),
      }),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    getFilterOptions: publicProcedure.output(z.object({
      campaigns: z.array(z.object({
        id: z.number(),
        name: z.string(),
      })),
      influencers: z.array(z.object({
        id: z.number(),
        name: z.string(),
      })),
      brands: z.array(z.object({
        id: z.number(),
        name: z.string(),
      })),
      periods: z.array(z.object({
        year: z.number(),
        month: z.number(),
        label: z.string(),
      })),
    })).query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    createInfluencerSettlement: publicProcedure.input(z.object({
      influencerId: z.number().int().positive(),
      periodYear: z.number().int().positive(),
      periodMonth: z.number().int().min(1).max(12),
      scheduledAt: z.string(),
    })).output(z.object({
      id: z.number(),
      success: z.boolean(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    createBrandSettlement: publicProcedure.input(z.object({
      brandId: z.number().int().positive(),
      periodYear: z.number().int().positive(),
      periodMonth: z.number().int().min(1).max(12),
      scheduledAt: z.string(),
    })).output(z.object({
      id: z.number(),
      success: z.boolean(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    completeInfluencerSettlements: publicProcedure.input(z.object({
      ids: z.array(z.number().int().positive()),
    })).output(z.object({
      success: z.boolean(),
      completedCount: z.number(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    completeBrandSettlements: publicProcedure.input(z.object({
      ids: z.array(z.number().int().positive()),
    })).output(z.object({
      success: z.boolean(),
      completedCount: z.number(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    exportToExcel: publicProcedure.input(z.object({
      settlementId: z.number().int().positive(),
      targetType: z.enum(['INFLUENCER', 'BRAND']),
    })).output(z.object({
      downloadUrl: z.string(),
      fileName: z.string(),
    })).mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
  })
});
export type AppRouter = typeof appRouter;

